version: '2'
services:
    relay:
        build: .
        volumes:
          - ./data:/data
        environment:
          - BTCD_TESTNET=1
        env_file:
          - variables.env
        ports:
          - 0.0.0.0:8333:8333
          - 0.0.0.0:18333:18333
        logging:
          driver: "json-file"
          options:
            max-size: "1m"
            max-file: "10"
